import type { AppUser } from "@/components/utilisateurs/types"

export const availableSites = ["Cristal", "Saphir"] as const
export const availableRoles = [
  "Exécutant",
  "Administrateur",
  "Dispatcheur",
  "Validateur",
  "Rédacteur",
  "Agent de réception",
] as const

export const appUsers: AppUser[] = [
  {
    id: "m-61089",
    code: "M-61089",
    fullName: "Joseph FONKOU",
    email: "josephfonkou@creaconsult.com",
    function: "Comptable",
    sites: ["Cristal", "Saphir"],
    roles: ["Exécutant", "Administrateur"],
    status: "actif",
    phone: "",
    createdBy: "Jason Adiogo",
    createdAt: "20 Juin 2026, 12:16",
    updatedAt: "27 Août 2026, 14:44",
  },
  {
    id: "m-61090",
    code: "M-61090",
    fullName: "Amina TRAORE",
    email: "amina.traore@creaconsult.com",
    function: "Analyste Financier",
    sites: ["Cristal"],
    roles: ["Validateur"],
    status: "actif",
    phone: "690 000 001",
    createdBy: "Jason Adiogo",
    createdAt: "15 Septembre 2026, 08:00",
    updatedAt: "15 Septembre 2026, 08:00",
  },
  {
    id: "m-61091",
    code: "M-61091",
    fullName: "Marc DELARUE",
    email: "marc.delarue@creaconsult.com",
    function: "Chef de Projet",
    sites: ["Cristal"],
    roles: ["Administrateur"],
    status: "actif",
    phone: "690 000 002",
    createdBy: "Jason Adiogo",
    createdAt: "01 Octobre 2026, 08:30",
    updatedAt: "01 Octobre 2026, 08:30",
  },
  {
    id: "m-61092",
    code: "M-61092",
    fullName: "Sofia MARTINEZ",
    email: "sofia.martinez@creaconsult.com",
    function: "Consultante RH",
    sites: ["Saphir"],
    roles: ["Rédacteur"],
    status: "actif",
    phone: "690 000 003",
    createdBy: "Jason Adiogo",
    createdAt: "12 Novembre 2026, 16:00",
    updatedAt: "12 Novembre 2026, 16:00",
  },
  {
    id: "m-61093",
    code: "M-61093",
    fullName: "Liam NGUYEN",
    email: "liam.nguyen@creaconsult.com",
    function: "Développeur",
    sites: ["Cristal", "Saphir"],
    roles: ["Exécutant"],
    status: "actif",
    phone: "690 000 004",
    createdBy: "Jason Adiogo",
    createdAt: "27 Septembre 2026, 15:00",
    updatedAt: "27 Septembre 2026, 15:00",
  },
  {
    id: "m-61094",
    code: "M-61094",
    fullName: "Emma DUPONT",
    email: "emma.dupont@creaconsult.com",
    function: "Designer UI/UX",
    sites: ["Cristal"],
    roles: ["Rédacteur"],
    status: "suspendu",
    phone: "690 000 005",
    createdBy: "Jason Adiogo",
    createdAt: "05 Octobre 2026, 11:50",
    updatedAt: "05 Octobre 2026, 11:50",
  },
]

export function getAppUser(id: string) {
  return appUsers.find((user) => user.id === id)
}
